services:
  telegram-bot-api:
    container_name: telegram-bot-api
    image: megurobot/telegram-bot-api:latest
    restart: unless-stopped
    environment:
      # "Rootless" mode with multiple containers or bind mount
      USER_GID: 1000
      USER_UID: 1000
      # Telegram client data
      TELEGRAM_API_ID: 123456
      TELEGRAM_API_HASH: abcdefghijklmnopqrstuvwyz123456789
      TELEGRAM_STAT: true
      TELEGRAM_LOCAL: true
    volumes:
      - telegram-bot-api:/var/lib/telegram-bot-api
    networks:
      telegram-bot-api:
    expose:
      - 8081:8081
      - 8082:8082

volumes:
  telegram-bot-api:
    name: telegram-bot-api
    external: true

networks:
  telegram-bot-api:
    name: telegram-bot-api
